In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
# File Paths

PLAYERS_PATH = "../data/raw/kaggle/players.csv"
TEAMS_PATH = "../data/raw/kaggle/teams.csv"
MATCHES_PATH = "../data/raw/kaggle/matches.csv"

# Read CSV Files

players = pd.read_csv(PLAYERS_PATH)
teams = pd.read_csv(TEAMS_PATH)
matches = pd.read_csv(MATCHES_PATH)

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

In [3]:
print("="*60)
print("PLAYERS DATASET")
print("="*60)
print(players.shape)

print()

print("="*60)
print("TEAMS DATASET")
print("="*60)
print(teams.shape)

print()

print("="*60)
print("MATCHES DATASET")
print("="*60)
print(matches.shape)

============================================================
PLAYERS DATASET
============================================================
(1248, 72)

============================================================
TEAMS DATASET
============================================================
(48, 136)

============================================================
MATCHES DATASET
============================================================
(104, 42)

In [4]:
print("PLAYERS")
display(players.head())

print("TEAMS")
display(teams.head())

print("MATCHES")
display(matches.head())

PLAYERS

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
0,Achref Abada,Algeria,Algeria,DF,26,1999,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adil Boulbina,Algeria,Algeria,FW,23,2003,NaN,2,0,19.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.0,NaN,0.00,0.00,NaN,NaN,10.0,5.3,NaN,0,2,10.0,2,0.0,0.0,0.0,0.0,0.00,1.06,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Amine Gouiri,Algeria,Algeria,FW,26,2000,Marseille,4,3,251.0,2.8,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.36,0.0,0.36,0.36,0.36,3.0,2.0,66.7,1.08,0.72,0.33,0.5,63.0,69.7,73.0,0,1,33.0,0,1.0,4.0,5.0,-1.0,-0.36,2.12,0.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anis Hadj Moussa,Algeria,Algeria,MF,24,2002,Feyenoord,3,1,98.0,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,2.0,0.0,0.0,1.84,0.00,0.00,NaN,33.0,27.2,63.0,0,2,18.0,1,1.0,1.0,2.0,-1.0,-0.92,0.11,0.0,0.0,2.0,0.0,5.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aïssa Mandi,Algeria,Algeria,DF,34,1991,Lille,4,4,360.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.0,NaN,0.00,0.00,NaN,NaN,90.0,100.0,90.0,4,0,NaN,0,1.0,5.0,9.0,-4.0,-1.00,NaN,0.0,0.0,5.0,0.0,0.0,4.0,3.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

TEAMS

,team,team_country,players_used,avg_age,possession,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,players_used_against,avg_age_against,possession_against,games_against,games_starts_against,minutes_against,minutes_90s_against,goals_against,assists_against,goals_assists_against,goals_pens_against,pens_made_against,pens_att_against,cards_yellow_against,cards_red_against,goals_per90_against,assists_per90_against,goals_assists_per90_against,goals_pens_per90_against,goals_assists_pens_per90_against,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,shots_against,shots_on_target_against,shots_on_target_pct_against,shots_per90_against,shots_on_target_per90_against,goals_per_shot_against,goals_per_shot_on_target_against,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,minutes_per_game_against,minutes_pct_against,minutes_per_start_against,games_complete_against,games_subs_against,minutes_per_sub_against,unused_subs_against,points_per_game_against,on_goals_for_against,on_goals_against_against,plus_minus_against,plus_minus_per90_against,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,cards_yellow_red_against,fouls_against,fouled_against,offsides_against,crosses_against,interceptions_against,tackles_won_against,pens_won_against,pens_conceded_against,own_goals_against,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct,gk_games_against,gk_games_starts_against,gk_minutes_against,gk_goals_against_against,gk_goals_against_per90_against,gk_shots_on_target_against_against,gk_saves_against,gk_save_pct_against,gk_wins_against,gk_ties_against,gk_losses_against,gk_clean_sheets_against,gk_clean_sheets_pct_against,gk_pens_att_against,gk_pens_allowed_against,gk_pens_saved_against,gk_pens_missed_against,gk_pens_save_pct_against
0,Algeria,Algeria,22,27.3,61.0,4,44,360,4.0,5,3,8,5,0,0,3,0,1.25,0.75,2.00,1.25,2.00,22,29.1,39.0,4,44,360,4.0,9,7,16,9,0,0,2,0,2.25,1.75,4.00,2.25,4.00,44,15,34.1,11.00,3.75,0.11,0.33,39,18,46.2,9.75,4.50,0.23,0.50,90,100,81,25,19,21,37,1.00,5,9,-4,-1.00,90,100,81,24,20,20,39,1.75,9,5,4,1.00,0,29,40,4,40,30,44,NaN,NaN,0,0,41,27,7,37,41,50,NaN,NaN,0,4,4,360,9,2.25,17,8,47.1,1,1,2,0,0.0,0,0,0,0,NaN,4,4,360,5,1.25,15,10,66.7,2,1,1,2,50.0,0,0,0,0,NaN
1,Argentina,Argentina,24,29.6,57.6,8,88,810,9.0,18,12,30,17,1,3,15,1,2.00,1.33,3.33,1.89,3.22,24,28.3,42.4,8,88,810,9.0,8,8,16,8,0,0,14,1,0.89,0.89,1.78,0.89,1.78,114,44,38.6,12.67,4.89,0.15,0.39,75,28,37.3,8.33,3.11,0.11,0.29,101,100,87,45,42,30,78,2.63,19,8,11,1.22,101,100,87,45,42,25,74,0.38,8,19,-11,-1.22,1,113,100,22,104,82,93,NaN,NaN,0,1,107,109,12,121,82,67,NaN,NaN,1,8,8,810,8,0.89,28,20,71.4,7,0,1,2,25.0,0,0,0,0,NaN,8,8,810,19,2.11,43,24,55.8,1,0,7,1,12.5,3,1,1,1,50.0
2,Australia,Australia,23,25.3,41.0,4,44,390,4.3,2,1,3,2,0,0,5,0,0.46,0.23,0.69,0.46,0.69,23,27.8,59.0,4,44,390,4.3,2,1,3,2,0,0,7,0,0.46,0.23,0.69,0.46,0.69,42,12,28.6,9.69,2.77,0.05,0.17,61,15,24.6,14.08,3.46,0.03,0.13,98,100,85,25,19,28,37,1.25,3,3,0,0.00,98,100,85,24,20,19,35,1.25,3,3,0,0.00,0,46,38,1,70,29,34,NaN,NaN,1,0,39,45,7,71,41,38,NaN,NaN,1,4,4,390,3,0.69,17,14,82.4,1,1,2,2,50.0,0,0,0,0,NaN,4,4,390,3,0.69,13,10,76.9,2,1,1,2,50.0,0,0,0,0,NaN
3,Austria,Austria,20,28.8,45.0,4,44,360,4.0,5,4,9,4,1,1,5,0,1.25,1.00,2.25,1.00,2.00,20,27.8,55.0,4,44,360,4.0,9,7,16,9,0,1,2,0,2.25,1.75,4.00,2.25,4.00,32,8,25.0,8.00,2.00,0.13,0.50,58,24,41.4,14.50,6.00,0.16,0.38,90,100,77,24,20,28,40,1.00,6,9,-3,-0.75,90,100,77,25,19,14,40,1.75,9,6,3,0.75,0,47,28,11,59,41,29,NaN,NaN,0,0,31,42,6,46,29,37,NaN,NaN,1,4,4,360,9,2.25,22,13,59.1,1,1,2,0,0.0,1,0,0,1,NaN,4,4,360,6,1.50,8,2,25.0,2,1,1,2,50.0,1,1,0,0,0.0
4,Belgium,Belgium,23,29.2,51.2,6,66,570,6.3,13,10,23,12,1,1,6,1,2.05,1.58,3.63,1.89,3.47,23,28.3,48.8,6,66,570,6.3,7,2,9,7,0,0,10,0,1.11,0.32,1.42,1.11,1.42,112,34,30.4,17.68,5.37,0.11,0.35,70,23,32.9,11.05,3.63,0.10,0.30,95,100,81,34,31,28,50,1.83,14,7,7,1.11,95,100,81,36,30,25,58,0.83,7,14,-7,-1.11,0,78,68,8,114,50,47,NaN,NaN,0,0,70,71,11,90,55,52,NaN,NaN,1,6,6,570,7,1.11,23,16,69.6,3,2,1,1,16.7,0,0,0,0,NaN,6,6,570,14,2.21,36,22,61.1,1,2,3,1,16.7,1,1,0,0,0.0

MATCHES

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,attendance,venue,referee,home_formation,away_formation,home_manager,away_manager,home_captain,away_captain,home_possession,away_possession,home_sot,away_sot,home_total_shots,away_total_shots,home_saves,away_saves,home_cards_yellow,away_cards_yellow,home_cards_red,away_cards_red,home_fouls,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1.0,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2.0,0.0,"80,824","Estadio Banorte, Coyoacán",Wilton Sampaio,4-1-4-1,5-3-2,Javier Aguirre,Hugo Broos,César Montes,Ronwen Williams,61,40,4,2,16,3,2,2,1,2,1,2,12,11,3,1,12,8,8,7,1.0,1.0,NaN
1,Group stage,1.0,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2.0,1.0,"44,985","Estadio Akron, Zapopan",Amin Omar,3-4-3,3-4-3,Hong Myung-bo,Miroslav Koubek,Son Heung-min,Ladislav Krejčí,62,38,6,4,15,7,3,4,1,0,0,0,9,16,4,5,12,15,11,7,2.0,2.0,NaN
2,Group stage,1.0,Fri,2026-06-12,15:00,Canada,Bosnia–Herz,1–1,1.0,1.0,"43,002","BMO Field, Toronto",Facundo Tello,4-2-2-2,4-2-2-2,Jesse Marsch,Sergej Barbarez,Stephen Eustáquio,Sead Kolašinac,61,39,4,3,13,8,2,1,2,3,0,0,10,20,9,4,24,10,4,10,1.0,0.0,NaN
3,Group stage,1.0,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4.0,1.0,"70,492","SoFi Stadium, Inglewood",Danny Makkelie,4-2-3-1,4-2-2-2,Mauricio Pochettino,Gustavo Alfaro,Tim Ream,Gustavo Gómez,65,35,6,1,16,9,0,3,1,5,0,0,13,17,3,1,17,5,11,9,2.0,1.0,NaN
4,Group stage,1.0,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1.0,1.0,"67,966","Levi's Stadium, Santa Clara",Said Martínez,4-1-4-1,4-2-3-1,Julen Lopetegui,Murat Yakin,Boualem Khoukhi,Granit Xhaka,32,68,4,7,7,26,5,3,2,1,0,0,12,11,3,10,8,35,10,7,0.0,1.0,NaN

In [5]:
print("PLAYERS")
display(players.tail())

print("TEAMS")
display(teams.tail())

print("MATCHES")
display(matches.tail())

PLAYERS

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
1243,Rustam Ashurmatov,Uzbekistan,Uzbekistan,DF,29,1996,Esteghlal,3,3,256.0,2.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,85.0,94.8,85.0,2,0,NaN,0,0.0,2.0,10.0,-8.0,-2.81,3.62,0.0,1.0,0.0,0.0,0.0,7.0,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1244,Sherzod Esanov,Uzbekistan,Uzbekistan,MF,23,2003,NaN,1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,1.0,0.4,NaN,0,1,1.0,2,0.0,0.0,0.0,0.0,0.00,3.01,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,Sherzod Nasrullaev,Uzbekistan,Uzbekistan,"DF,MF",27,1998,NaN,3,3,180.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,100.0,0.5,0.5,0.0,0.0,60.0,66.7,60.0,1,0,NaN,0,0.0,1.0,7.0,-6.0,-3.00,0.00,0.0,3.0,2.0,0.0,3.0,2.0,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1246,Umar Eshmurodov,Uzbekistan,Uzbekistan,DF,33,1992,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,Utkir Yusupov,Uzbekistan,Uzbekistan,GK,35,1991,NaN,1,1,90.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,90.0,33.3,90.0,1,0,NaN,2,0.0,1.0,3.0,-2.0,-2.00,1.50,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,1.0,1.0,90.0,3.0,3.0,4.0,1.0,25.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

TEAMS

,team,team_country,players_used,avg_age,possession,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,players_used_against,avg_age_against,possession_against,games_against,games_starts_against,minutes_against,minutes_90s_against,goals_against,assists_against,goals_assists_against,goals_pens_against,pens_made_against,pens_att_against,cards_yellow_against,cards_red_against,goals_per90_against,assists_per90_against,goals_assists_per90_against,goals_pens_per90_against,goals_assists_pens_per90_against,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,shots_against,shots_on_target_against,shots_on_target_pct_against,shots_per90_against,shots_on_target_per90_against,goals_per_shot_against,goals_per_shot_on_target_against,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,minutes_per_game_against,minutes_pct_against,minutes_per_start_against,games_complete_against,games_subs_against,minutes_per_sub_against,unused_subs_against,points_per_game_against,on_goals_for_against,on_goals_against_against,plus_minus_against,plus_minus_per90_against,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,cards_yellow_red_against,fouls_against,fouled_against,offsides_against,crosses_against,interceptions_against,tackles_won_against,pens_won_against,pens_conceded_against,own_goals_against,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct,gk_games_against,gk_games_starts_against,gk_minutes_against,gk_goals_against_against,gk_goals_against_per90_against,gk_shots_on_target_against_against,gk_saves_against,gk_save_pct_against,gk_wins_against,gk_ties_against,gk_losses_against,gk_clean_sheets_against,gk_clean_sheets_pct_against,gk_pens_att_against,gk_pens_allowed_against,gk_pens_saved_against,gk_pens_missed_against,gk_pens_save_pct_against
43,Tunisia,Tunisia,20,27.4,39.3,3,33,270,3.0,2,2,4,2,0,0,1,0,0.67,0.67,1.33,0.67,1.33,20,27.4,60.7,3,33,270,3.0,11,10,21,11,0,0,0,0,3.67,3.33,7.00,3.67,7.00,18,6,33.3,6.00,2.00,0.11,0.33,44,19,43.2,14.67,6.33,0.25,0.58,90,100,82,18,15,18,28,0.00,2,12,-10,-3.33,90,100,82,18,15,14,28,3.00,12,2,10,3.33,0,27,32,9,36,27,36,NaN,NaN,1,0,35,27,5,51,24,25,NaN,NaN,0,3,3,270,12,4.00,18,6,33.3,0,0,3,0,0.0,0,0,0,0,NaN,3,3,270,2,0.67,6,4,66.7,3,0,0,1,33.3,0,0,0,0,NaN
44,Türkiye,Turkey,23,26.6,66.3,3,33,270,3.0,3,3,6,3,0,0,2,0,1.00,1.00,2.00,1.00,2.00,23,26.1,33.7,3,33,270,3.0,5,3,8,5,0,0,2,1,1.67,1.00,2.67,1.67,2.67,71,16,22.5,23.67,5.33,0.04,0.19,34,13,38.2,11.33,4.33,0.15,0.38,90,100,82,18,15,17,30,1.00,3,5,-2,-0.67,90,100,82,17,15,16,29,2.00,5,3,2,0.67,0,31,38,7,79,18,39,NaN,NaN,0,0,40,30,9,38,26,29,NaN,NaN,0,3,3,270,5,1.67,13,8,61.5,1,0,2,0,0.0,0,0,0,0,NaN,3,3,270,3,1.00,16,13,81.3,2,0,1,2,66.7,0,0,0,0,NaN
45,United States,United States,24,26.7,56.8,5,55,450,5.0,9,4,13,9,0,0,7,1,1.80,0.80,2.60,1.80,2.60,24,27.0,43.2,5,55,450,5.0,8,8,16,8,0,0,11,0,1.60,1.60,3.20,1.60,3.20,59,19,32.2,11.80,3.80,0.15,0.47,48,16,33.3,9.60,3.20,0.17,0.50,90,100,84,32,22,15,48,1.80,11,8,3,0.60,90,100,84,30,25,23,50,1.20,8,11,-3,-0.60,0,56,66,11,74,60,42,NaN,NaN,0,0,68,53,4,62,41,69,NaN,NaN,2,5,5,450,8,1.60,16,8,50.0,3,0,2,2,40.0,0,0,0,0,NaN,5,5,450,11,2.20,21,10,47.6,2,0,3,0,0.0,0,0,0,0,NaN
46,Uruguay,Uruguay,17,28.6,55.0,3,33,270,3.0,3,1,4,3,0,0,5,1,1.00,0.33,1.33,1.00,1.33,17,28.7,45.0,3,33,270,3.0,4,1,5,4,0,0,4,0,1.33,0.33,1.67,1.33,1.67,49,13,26.5,16.33,4.33,0.06,0.23,25,8,32.0,8.33,2.67,0.16,0.50,90,100,80,20,12,27,29,0.67,3,4,-1,-0.33,90,100,80,18,15,20,30,1.67,4,3,1,0.33,0,31,29,14,92,32,25,NaN,NaN,0,0,29,30,2,26,29,34,NaN,NaN,0,3,3,270,4,1.33,8,4,50.0,0,2,1,0,0.0,0,0,0,0,NaN,3,3,270,3,1.00,14,10,78.6,1,2,0,1,33.3,0,0,0,0,NaN
47,Uzbekistan,Uzbekistan,23,26.9,38.3,3,33,270,3.0,2,1,3,2,0,0,4,0,0.67,0.33,1.00,0.67,1.00,23,28.8,61.7,3,33,270,3.0,10,6,16,9,1,1,5,0,3.33,2.00,5.33,3.00,5.00,18,5,27.8,6.00,1.67,0.11,0.40,51,17,33.3,17.00,5.67,0.18,0.53,90,100,80,18,15,22,30,0.00,2,11,-9,-3.00,90,100,80,18,15,19,30,3.00,11,2,9,3.00,0,45,29,3,37,33,39,NaN,NaN,1,0,31,43,8,58,18,28,NaN,NaN,0,3,3,270,11,3.67,17,6,35.3,0,0,3,0,0.0,1,1,0,0,0.0,3,3,270,2,0.67,6,4,66.7,3,0,0,1,33.3,0,0,0,0,NaN

MATCHES

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,attendance,venue,referee,home_formation,away_formation,home_manager,away_manager,home_captain,away_captain,home_possession,away_possession,home_sot,away_sot,home_total_shots,away_total_shots,home_saves,away_saves,home_cards_yellow,away_cards_yellow,home_cards_red,away_cards_red,home_fouls,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
99,Quarter-finals,NaN,Sat,2026-07-11,20:00,Argentina,Switzerland,3–1,3.0,1.0,"69,045","GEHA Field at Arrowhead Stadium, Kansas City",João Pinheiro,4-1-3-2,4-2-3-1,Lionel Scaloni,Murat Yakin,Lionel Messi,Granit Xhaka,59,41,7,5,22,11,4,4,3,2,0,1,14,18,8,2,22,19,12,6,4.0,3.0,Required Extra Time
100,Semi-finals,NaN,Tue,2026-07-14,14:00,France,Spain,0–2,0.0,2.0,"70,176","AT&T Stadium, Arlington",Iván Barton,4-2-3-1,4-2-3-1,Didier Deschamps,Luis de la Fuente,Kylian Mbappé,Rodri,49,51,3,2,10,10,0,3,2,1,0,0,11,12,7,1,20,8,8,7,4.0,5.0,NaN
101,Semi-finals,NaN,Wed,2026-07-15,15:00,England,Argentina,1–2,1.0,2.0,"68,239","Mercedes-Benz Stadium, Atlanta",Ismail Elfath,4-2-3-1,4-1-4-1,Thomas Tuchel,Lionel Scaloni,Harry Kane,Lionel Messi,36,64,2,5,5,15,3,1,1,3,0,0,11,15,1,6,15,19,9,6,1.0,3.0,NaN
102,Third-place match,NaN,Sat,2026-07-18,17:00,France,England,4–6,4.0,6.0,"64,478","Hard Rock Stadium, Miami Gardens",Jesús Valenzuela,4-2-3-1,4-1-4-1,Didier Deschamps,Thomas Tuchel,Kylian Mbappé,Declan Rice,46,54,9,11,19,19,4,5,0,0,0,0,14,8,3,4,6,12,8,11,3.0,3.0,NaN
103,Final,NaN,Sun,2026-07-19,15:00,Spain,Argentina,1–0,1.0,0.0,"80,663","MetLife Stadium, East Rutherford",Slavko Vinčič,4-2-3-1,4-2-2-2,Luis de la Fuente,Lionel Scaloni,Rodri,Lionel Messi,65,35,12,0,20,2,0,11,0,7,0,1,21,25,9,4,27,8,11,16,4.0,1.0,Required Extra Time

In [6]:
print("="*60)
print("PLAYERS COLUMNS")
print("="*60)

for column in players.columns:
    print(column)

print("\n")

print("="*60)
print("TEAMS COLUMNS")
print("="*60)

for column in teams.columns:
    print(column)

print("\n")

print("="*60)
print("MATCHES COLUMNS")
print("="*60)

for column in matches.columns:
    print(column)

============================================================
PLAYERS COLUMNS
============================================================
player
team
team_country
position
age
birth_year
club
games
games_starts
minutes
minutes_90s
goals
assists
goals_assists
goals_pens
pens_made
pens_att
cards_yellow
cards_red
goals_per90
assists_per90
goals_assists_per90
goals_pens_per90
goals_assists_pens_per90
shots
shots_on_target
shots_on_target_pct
shots_per90
shots_on_target_per90
goals_per_shot
goals_per_shot_on_target
minutes_per_game
minutes_pct
minutes_per_start
games_complete
games_subs
minutes_per_sub
unused_subs
points_per_game
on_goals_for
on_goals_against
plus_minus
plus_minus_per90
plus_minus_wowy
cards_yellow_red
fouls
fouled
offsides
crosses
interceptions
tackles_won
pens_won
pens_conceded
own_goals
gk_games
gk_games_starts
gk_minutes
gk_goals_against
gk_goals_against_per90
gk_shots_on_target_against
gk_saves
gk_save_pct
gk_wins
gk_ties
gk_losses
gk_clean_sheets
gk_clean_sheets_pct
gk_pens_att
gk_pens_allowed
gk_pens_saved
gk_pens_missed
gk_pens_save_pct


============================================================
TEAMS COLUMNS
============================================================
team
team_country
players_used
avg_age
possession
games
games_starts
minutes
minutes_90s
goals
assists
goals_assists
goals_pens
pens_made
pens_att
cards_yellow
cards_red
goals_per90
assists_per90
goals_assists_per90
goals_pens_per90
goals_assists_pens_per90
players_used_against
avg_age_against
possession_against
games_against
games_starts_against
minutes_against
minutes_90s_against
goals_against
assists_against
goals_assists_against
goals_pens_against
pens_made_against
pens_att_against
cards_yellow_against
cards_red_against
goals_per90_against
assists_per90_against
goals_assists_per90_against
goals_pens_per90_against
goals_assists_pens_per90_against
shots
shots_on_target
shots_on_target_pct
shots_per90
shots_on_target_per90
goals_per_shot
goals_per_shot_on_target
shots_against
shots_on_target_against
shots_on_target_pct_against
shots_per90_against
shots_on_target_per90_against
goals_per_shot_against
goals_per_shot_on_target_against
minutes_per_game
minutes_pct
minutes_per_start
games_complete
games_subs
minutes_per_sub
unused_subs
points_per_game
on_goals_for
on_goals_against
plus_minus
plus_minus_per90
minutes_per_game_against
minutes_pct_against
minutes_per_start_against
games_complete_against
games_subs_against
minutes_per_sub_against
unused_subs_against
points_per_game_against
on_goals_for_against
on_goals_against_against
plus_minus_against
plus_minus_per90_against
cards_yellow_red
fouls
fouled
offsides
crosses
interceptions
tackles_won
pens_won
pens_conceded
own_goals
cards_yellow_red_against
fouls_against
fouled_against
offsides_against
crosses_against
interceptions_against
tackles_won_against
pens_won_against
pens_conceded_against
own_goals_against
gk_games
gk_games_starts
gk_minutes
gk_goals_against
gk_goals_against_per90
gk_shots_on_target_against
gk_saves
gk_save_pct
gk_wins
gk_ties
gk_losses
gk_clean_sheets
gk_clean_sheets_pct
gk_pens_att
gk_pens_allowed
gk_pens_saved
gk_pens_missed
gk_pens_save_pct
gk_games_against
gk_games_starts_against
gk_minutes_against
gk_goals_against_against
gk_goals_against_per90_against
gk_shots_on_target_against_against
gk_saves_against
gk_save_pct_against
gk_wins_against
gk_ties_against
gk_losses_against
gk_clean_sheets_against
gk_clean_sheets_pct_against
gk_pens_att_against
gk_pens_allowed_against
gk_pens_saved_against
gk_pens_missed_against
gk_pens_save_pct_against


============================================================
MATCHES COLUMNS
============================================================
round
gameweek
dayofweek
date
start_time
home_team
away_team
score
home_score
away_score
attendance
venue
referee
home_formation
away_formation
home_manager
away_manager
home_captain
away_captain
home_possession
away_possession
home_sot
away_sot
home_total_shots
away_total_shots
home_saves
away_saves
home_cards_yellow
away_cards_yellow
home_cards_red
away_cards_red
home_fouls
away_fouls
home_corners
away_corners
home_crosses
away_crosses
home_interceptions
away_interceptions
home_offsides
away_offsides
notes

In [7]:
print("="*60)
print("PLAYERS INFO")
print("="*60)

players.info()

print("\n")

print("="*60)
print("TEAMS INFO")
print("="*60)

teams.info()

print("\n")

print("="*60)
print("MATCHES INFO")
print("="*60)

matches.info()

============================================================
PLAYERS INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 72 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   player                      1248 non-null   str
 1   team                        1248 non-null   str
 2   team_country                1248 non-null   str
 3   position                    1248 non-null   str
 4   age                         1248 non-null   int64
 5   birth_year                  1248 non-null   int64
 6   club                        907 non-null    str
 7   games                       1248 non-null   int64
 8   games_starts                1248 non-null   int64
 9   minutes                     1039 non-null   float64
 10  minutes_90s                 1039 non-null   float64
 11  goals                       1039 non-null   float64
 12  assists                     1039 non-null   float64
 13  goals_assists               1039 non-null   float64
 14  goals_pens                  1039 non-null   float64
 15  pens_made                   1039 non-null   float64
 16  pens_att                    1039 non-null   float64
 17  cards_yellow                1039 non-null   float64
 18  cards_red                   1039 non-null   float64
 19  goals_per90                 1039 non-null   float64
 20  assists_per90               1039 non-null   float64
 21  goals_assists_per90         1039 non-null   float64
 22  goals_pens_per90            1039 non-null   float64
 23  goals_assists_pens_per90    1039 non-null   float64
 24  shots                       1039 non-null   float64
 25  shots_on_target             1039 non-null   float64
 26  shots_on_target_pct         680 non-null    float64
 27  shots_per90                 1039 non-null   float64
 28  shots_on_target_per90       1039 non-null   float64
 29  goals_per_shot              680 non-null    float64
 30  goals_per_shot_on_target    396 non-null    float64
 31  minutes_per_game            1039 non-null   float64
 32  minutes_pct                 1039 non-null   float64
 33  minutes_per_start           781 non-null    float64
 34  games_complete              1248 non-null   int64
 35  games_subs                  1248 non-null   int64
 36  minutes_per_sub             578 non-null    float64
 37  unused_subs                 1248 non-null   int64
 38  points_per_game             1039 non-null   float64
 39  on_goals_for                1039 non-null   float64
 40  on_goals_against            1039 non-null   float64
 41  plus_minus                  1039 non-null   float64
 42  plus_minus_per90            1039 non-null   float64
 43  plus_minus_wowy             920 non-null    float64
 44  cards_yellow_red            1039 non-null   float64
 45  fouls                       1039 non-null   float64
 46  fouled                      1039 non-null   float64
 47  offsides                    1039 non-null   float64
 48  crosses                     1039 non-null   float64
 49  interceptions               1039 non-null   float64
 50  tackles_won                 1039 non-null   float64
 51  pens_won                    0 non-null      float64
 52  pens_conceded               0 non-null      float64
 53  own_goals                   1039 non-null   float64
 54  gk_games                    62 non-null     float64
 55  gk_games_starts             62 non-null     float64
 56  gk_minutes                  62 non-null     float64
 57  gk_goals_against            62 non-null     float64
 58  gk_goals_against_per90      62 non-null     float64
 59  gk_shots_on_target_against  62 non-null     float64
 60  gk_saves                    62 non-null     float64
 61  gk_save_pct                 59 non-null     float64
 62  gk_wins                     62 non-null     float64
 63  gk_ties                     62 non-null     float64
 64  gk_losses                   62 non-null     float64
 65  gk_clean_sheets             62 non-null     float64
 66  gk_clean_sheets_pct         58 non-null     float64
 67  gk_pens_att                 62 non-null     float64
 68  gk_pens_allowed             62 non-null     float64
 69  gk_pens_saved               62 non-null     float64
 70  gk_pens_missed              62 non-null     float64
 71  gk_pens_save_pct            15 non-null     float64
dtypes: float64(60), int64(7), str(5)
memory usage: 702.1 KB


============================================================
TEAMS INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Columns: 136 entries, team to gk_pens_save_pct_against
dtypes: float64(42), int64(92), str(2)
memory usage: 51.1 KB


============================================================
MATCHES INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   round               104 non-null    str
 1   gameweek            72 non-null     float64
 2   dayofweek           104 non-null    str
 3   date                104 non-null    str
 4   start_time          104 non-null    str
 5   home_team           104 non-null    str
 6   away_team           104 non-null    str
 7   score               104 non-null    str
 8   home_score          100 non-null    float64
 9   away_score          100 non-null    float64
 10  attendance          104 non-null    str
 11  venue               104 non-null    str
 12  referee             104 non-null    str
 13  home_formation      104 non-null    str
 14  away_formation      104 non-null    str
 15  home_manager        104 non-null    str
 16  away_manager        104 non-null    str
 17  home_captain        104 non-null    str
 18  away_captain        104 non-null    str
 19  home_possession     104 non-null    int64
 20  away_possession     104 non-null    int64
 21  home_sot            104 non-null    int64
 22  away_sot            104 non-null    int64
 23  home_total_shots    104 non-null    int64
 24  away_total_shots    104 non-null    int64
 25  home_saves          104 non-null    int64
 26  away_saves          104 non-null    int64
 27  home_cards_yellow   104 non-null    int64
 28  away_cards_yellow   104 non-null    int64
 29  home_cards_red      104 non-null    int64
 30  away_cards_red      104 non-null    int64
 31  home_fouls          104 non-null    int64
 32  away_fouls          104 non-null    int64
 33  home_corners        104 non-null    int64
 34  away_corners        104 non-null    int64
 35  home_crosses        104 non-null    int64
 36  away_crosses        104 non-null    int64
 37  home_interceptions  104 non-null    int64
 38  away_interceptions  104 non-null    int64
 39  home_offsides       99 non-null     float64
 40  away_offsides       99 non-null     float64
 41  notes               9 non-null      str
dtypes: float64(5), int64(20), str(17)
memory usage: 34.3 KB

In [8]:
print("PLAYERS")
display(players.dtypes)

print("TEAMS")
display(teams.dtypes)

print("MATCHES")
display(matches.dtypes)

PLAYERS

player                            str
team                              str
team_country                      str
position                          str
age                             int64
birth_year                      int64
club                              str
games                           int64
games_starts                    int64
minutes                       float64
minutes_90s                   float64
goals                         float64
assists                       float64
goals_assists                 float64
goals_pens                    float64
pens_made                     float64
pens_att                      float64
cards_yellow                  float64
cards_red                     float64
goals_per90                   float64
assists_per90                 float64
goals_assists_per90           float64
goals_pens_per90              float64
goals_assists_pens_per90      float64
shots                         float64
shots_on_target               float64
shots_on_target_pct           float64
shots_per90                   float64
shots_on_target_per90         float64
goals_per_shot                float64
goals_per_shot_on_target      float64
minutes_per_game              float64
minutes_pct                   float64
minutes_per_start             float64
games_complete                  int64
games_subs                      int64
minutes_per_sub               float64
unused_subs                     int64
points_per_game               float64
on_goals_for                  float64
on_goals_against              float64
plus_minus                    float64
plus_minus_per90              float64
plus_minus_wowy               float64
cards_yellow_red              float64
fouls                         float64
fouled                        float64
offsides                      float64
crosses                       float64
interceptions                 float64
tackles_won                   float64
pens_won                      float64
pens_conceded                 float64
own_goals                     float64
gk_games                      float64
gk_games_starts               float64
gk_minutes                    float64
gk_goals_against              float64
gk_goals_against_per90        float64
gk_shots_on_target_against    float64
gk_saves                      float64
gk_save_pct                   float64
gk_wins                       float64
gk_ties                       float64
gk_losses                     float64
gk_clean_sheets               float64
gk_clean_sheets_pct           float64
gk_pens_att                   float64
gk_pens_allowed               float64
gk_pens_saved                 float64
gk_pens_missed                float64
gk_pens_save_pct              float64
dtype: object

TEAMS

team                            str
team_country                    str
players_used                  int64
avg_age                     float64
possession                  float64
                             ...
gk_pens_att_against           int64
gk_pens_allowed_against       int64
gk_pens_saved_against         int64
gk_pens_missed_against        int64
gk_pens_save_pct_against    float64
Length: 136, dtype: object

MATCHES

round                     str
gameweek              float64
dayofweek                 str
date                      str
start_time                str
home_team                 str
away_team                 str
score                     str
home_score            float64
away_score            float64
attendance                str
venue                     str
referee                   str
home_formation            str
away_formation            str
home_manager              str
away_manager              str
home_captain              str
away_captain              str
home_possession         int64
away_possession         int64
home_sot                int64
away_sot                int64
home_total_shots        int64
away_total_shots        int64
home_saves              int64
away_saves              int64
home_cards_yellow       int64
away_cards_yellow       int64
home_cards_red          int64
away_cards_red          int64
home_fouls              int64
away_fouls              int64
home_corners            int64
away_corners            int64
home_crosses            int64
away_crosses            int64
home_interceptions      int64
away_interceptions      int64
home_offsides         float64
away_offsides         float64
notes                     str
dtype: object

In [9]:
print("="*60)
print("PLAYERS MISSING VALUES")
print("="*60)

display(players.isnull().sum().sort_values(ascending=False))

print()

print("="*60)
print("TEAMS MISSING VALUES")
print("="*60)

display(teams.isnull().sum().sort_values(ascending=False))

print()

print("="*60)
print("MATCHES MISSING VALUES")
print("="*60)

display(matches.isnull().sum().sort_values(ascending=False))

============================================================
PLAYERS MISSING VALUES
============================================================

pens_conceded                 1248
pens_won                      1248
gk_pens_save_pct              1233
gk_clean_sheets_pct           1190
gk_save_pct                   1189
gk_wins                       1186
gk_ties                       1186
gk_clean_sheets               1186
gk_pens_missed                1186
gk_pens_saved                 1186
gk_pens_allowed               1186
gk_pens_att                   1186
gk_shots_on_target_against    1186
gk_saves                      1186
gk_goals_against_per90        1186
gk_goals_against              1186
gk_games                      1186
gk_games_starts               1186
gk_losses                     1186
gk_minutes                    1186
goals_per_shot_on_target       852
minutes_per_sub                670
shots_on_target_pct            568
goals_per_shot                 568
minutes_per_start              467
club                           341
plus_minus_wowy                328
goals_assists                  209
minutes_pct                    209
points_per_game                209
shots_on_target_per90          209
goals_pens                     209
pens_att                       209
pens_made                      209
cards_red                      209
cards_yellow                   209
assists_per90                  209
minutes                        209
goals                          209
minutes_90s                    209
plus_minus_per90               209
plus_minus                     209
on_goals_against               209
tackles_won                    209
assists                        209
own_goals                      209
interceptions                  209
on_goals_for                   209
shots                          209
shots_per90                    209
shots_on_target                209
goals_per90                    209
goals_pens_per90               209
goals_assists_per90            209
goals_assists_pens_per90       209
minutes_per_game               209
cards_yellow_red               209
fouls                          209
fouled                         209
offsides                       209
crosses                        209
team                             0
player                           0
team_country                     0
games                            0
birth_year                       0
age                              0
position                         0
unused_subs                      0
games_subs                       0
games_complete                   0
games_starts                     0
dtype: int64

============================================================
TEAMS MISSING VALUES
============================================================

pens_won                    48
pens_conceded_against       48
pens_won_against            48
pens_conceded               48
gk_pens_save_pct_against    33
                            ..
gk_clean_sheets_against      0
gk_pens_att_against          0
gk_pens_allowed_against      0
gk_pens_saved_against        0
gk_pens_missed_against       0
Length: 136, dtype: int64

============================================================
MATCHES MISSING VALUES
============================================================

notes                 95
gameweek              32
home_offsides          5
away_offsides          5
away_score             4
home_score             4
home_team              0
round                  0
dayofweek              0
date                   0
away_team              0
score                  0
start_time             0
attendance             0
away_formation         0
venue                  0
referee                0
home_formation         0
away_captain           0
home_possession        0
away_possession        0
home_sot               0
away_sot               0
home_manager           0
away_manager           0
home_captain           0
home_saves             0
away_total_shots       0
home_total_shots       0
away_saves             0
away_cards_red         0
home_cards_yellow      0
away_cards_yellow      0
home_cards_red         0
home_corners           0
away_fouls             0
home_fouls             0
away_corners           0
home_interceptions     0
away_crosses           0
home_crosses           0
away_interceptions     0
dtype: int64

In [10]:
print("Players Duplicate Rows :", players.duplicated().sum())

print("Teams Duplicate Rows :", teams.duplicated().sum())

print("Matches Duplicate Rows :", matches.duplicated().sum())

Players Duplicate Rows : 0
Teams Duplicate Rows : 0
Matches Duplicate Rows : 0

In [11]:
print("="*60)
print("PLAYERS")
print("="*60)

display(players.describe(include="all"))

print("="*60)
print("TEAMS")
print("="*60)

display(teams.describe(include="all"))

print("="*60)
print("MATCHES")
print("="*60)

display(matches.describe(include="all"))

============================================================
PLAYERS
============================================================

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct
count,1248,1248,1248,1248,1248.000000,1248.000000,907,1248.000000,1248.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,680.000000,1039.000000,1039.000000,680.000000,396.000000,1039.000000,1039.000000,781.000000,1248.000000,1248.000000,578.000000,1248.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,920.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,0.0,0.0,1039.000000,62.000000,62.000000,62.000000,62.000000,62.00000,62.000000,62.000000,59.000000,62.000000,62.000000,62.000000,62.000000,58.000000,62.000000,62.000000,62.000000,62.000000,15.000000
unique,1247,48,48,9,NaN,NaN,315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Emiliano Martínez,Algeria,Algeria,MF,NaN,NaN,Manchester City,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,26,26,378,NaN,NaN,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,27.456731,1998.040865,NaN,2.634615,1.833333,203.474495,2.259865,0.283927,0.215592,0.499519,0.268527,0.015399,0.021174,0.259865,0.014437,0.139875,0.089923,0.229865,0.134235,0.224216,2.481232,0.852743,30.109559,1.316362,0.411954,0.086441,0.293384,57.852743,50.705197,79.592830,1.024038,0.801282,22.477509,1.629808,1.181453,3.256015,3.238691,0.017324,-0.552281,-0.156022,0.001925,2.321463,2.221367,0.354187,3.205005,1.673725,1.948989,NaN,NaN,0.012512,3.467742,3.354839,310.645161,4.967742,1.80629,14.258065,9.274194,61.135593,1.290323,0.774194,1.290323,0.919355,21.165517,0.354839,0.258065,0.080645,0.016129,18.886667
std,NaN,NaN,NaN,NaN,4.271243,4.257633,NaN,1.924265,1.896549,158.361191,1.757987,0.834724,0.590310,1.169519,0.786495,0.130781,0.162869,0.511747,0.119341,0.989740,0.314995,1.043094,0.985793,1.039396,3.799577,1.807837,32.392004,2.539285,1.224529,0.186523,0.382996,29.002366,34.143862,14.122837,1.544652,1.120888,14.048456,1.791670,0.903475,3.718140,2.708512,3.580036,7.042085,8.377231,0.043853,2.489019,2.833036,0.886453,5.676349,2.200103,2.493208,NaN,NaN,0.119558,1.799068,1.934135,182.624680,2.528317,1.27331,7.140132,5.668924,19.148456,1.730982,0.912919,0.797272,1.334269,26.240671,0.679845,0.541264,0.328852,0.127000,36.113212
min,NaN,NaN,NaN,NaN,17.000000,1982.000000,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.100000,12.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,-11.000000,-90.000000,-90.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,1.000000,0.000000,2.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,24.000000,1995.000000,NaN,1.000000,0.000000,71.000000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32.500000,16.850000,71.000000,0.000000,0.000000,12.000000,0.000000,0.330000,1.000000,1.000000,-2.000000,-1.330000,-1.450000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,2.000000,2.000000,180.000000,3.000000,1.00000,9.250000,5.000000,53.450000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,27.000000,1998.000000,NaN,3.000000,1.000000,180.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,25.000000,0.670000,0.000000,0.000000,0.000000,63.000000,50.000000,84.000000,0.000000,0.000000,20.000000,1.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,1.000000,1.000000,1.000000,NaN,NaN,0.000000,3.000000,3.000000,270.000000,5.000000,1.28000,14.000000,8.500000,63.600000,1.000000,0.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,30.000000,2001.000000,NaN,4.000000,3.000000,288.000000,3.200000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.230000,0.000000,0.210000,3.000000,1.000000,50.000000,1.755000,0.485000,0.080000,0.500000,86.000000,82.950000,90.000000,2.000000,1.000000,31.000000,3.000000,1.830000,5.000000,5.000000,2.000000,0.820000,1.470000,0.000000,4.000000,3.000000,0.000000,4.000000,2.000000,3.000000,NaN,NaN,0.000000,4.000000,4.000000,390.000000,6.750000,2.67000,19.750000,13.750000,73.500000,2.000000,1.000000,2.000000,2.000000,38.325000,0.750000,0.000000,0.000000,0.000000,16.650000
max,NaN,NaN,NaN,NaN,43.000000,2008.000000,NaN,8.000000,8.000000,810.000000,9.000000,10.000000,7.000000,14.000000,9.000000,2.000000,2.000000,3.000000,1.000000,30.000000,4.500000,30.000000,30.000000,30.000000,41.000000,23.000000,100.000000,45.000000,30.000000,1.000000,1.000000,105.000000,100.000000,120.000000,8.000000,7.000000,78.000000,8.000000,3.000000,20.000000,12.000000,13.000000,90.000000,91.000000,1.000000,15.000000,20.000000,9.000000,54.000000,15.000000,20.000000,NaN,NaN,2.000000,8.000000,8.000000,810.000000,10.000000,5.33000,29.000000,23.000000,90.900000,7.000000,3.000000,3.000000,7.000000,100.000000,3.000000,2.000000,2.000000,1.000000,100.000000

============================================================
TEAMS
============================================================

,team,team_country,players_used,avg_age,possession,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,players_used_against,avg_age_against,possession_against,games_against,games_starts_against,minutes_against,minutes_90s_against,goals_against,assists_against,goals_assists_against,goals_pens_against,pens_made_against,pens_att_against,cards_yellow_against,cards_red_against,goals_per90_against,assists_per90_against,goals_assists_per90_against,goals_pens_per90_against,goals_assists_pens_per90_against,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,shots_against,shots_on_target_against,shots_on_target_pct_against,shots_per90_against,shots_on_target_per90_against,goals_per_shot_against,goals_per_shot_on_target_against,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,minutes_per_game_against,minutes_pct_against,minutes_per_start_against,games_complete_against,games_subs_against,minutes_per_sub_against,unused_subs_against,points_per_game_against,on_goals_for_against,on_goals_against_against,plus_minus_against,plus_minus_per90_against,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,cards_yellow_red_against,fouls_against,fouled_against,offsides_against,crosses_against,interceptions_against,tackles_won_against,pens_won_against,pens_conceded_against,own_goals_against,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct,gk_games_against,gk_games_starts_against,gk_minutes_against,gk_goals_against_against,gk_goals_against_per90_against,gk_shots_on_target_against_against,gk_saves_against,gk_save_pct_against,gk_wins_against,gk_ties_against,gk_losses_against,gk_clean_sheets_against,gk_clean_sheets_pct_against,gk_pens_att_against,gk_pens_allowed_against,gk_pens_saved_against,gk_pens_missed_against,gk_pens_save_pct_against
count,48,48,48.000000,48.000000,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.0,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.0,48.000000,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,0.0,0.0,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,0.0,0.0,48.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,15.000000,48.000000,48.000000,48.00000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,15.000000
unique,48,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Algeria,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,21.645833,27.939583,48.629167,4.333333,47.666667,401.25000,4.450000,6.145833,4.666667,10.812500,5.81250,0.333333,0.458333,5.625000,0.312500,1.227083,0.929375,2.155833,1.169583,2.098333,21.645833,27.889583,51.389583,4.333333,47.666667,401.25000,4.450000,6.145833,4.666667,10.81250,5.812500,0.333333,0.458333,5.770833,0.312500,1.531875,1.149583,2.682292,1.450833,2.600625,53.708333,18.458333,32.710417,11.53375,3.815625,0.102083,0.310000,53.708333,18.458333,34.900000,12.771250,4.448542,0.114792,0.318125,92.125000,100.0,82.104167,26.625000,20.833333,22.291667,42.375000,1.177292,6.416667,6.416667,0.000000,-0.322708,92.125000,100.0,82.104167,26.625000,20.833333,22.020833,42.37500,1.580417,6.416667,6.416667,0.000000,0.322708,0.041667,50.250000,48.083333,7.666667,69.375000,36.229167,42.187500,NaN,NaN,0.270833,0.041667,50.250000,48.083333,7.666667,69.375000,36.229167,42.187500,NaN,NaN,0.270833,4.333333,4.333333,401.25000,6.416667,1.605208,18.416667,11.979167,64.839583,1.750000,0.833333,1.750000,1.145833,22.687500,0.458333,0.333333,0.104167,0.020833,18.886667,4.333333,4.333333,401.25000,6.416667,1.282292,18.416667,11.979167,66.070833,1.750000,0.833333,1.750000,1.145833,30.350000,0.458333,0.333333,0.104167,0.020833,23.333333
std,NaN,NaN,1.973113,1.355954,9.455741,1.448893,15.937822,143.09088,1.584096,5.010583,4.117081,9.033404,4.62949,0.630209,0.797825,2.646756,0.551834,0.683371,0.629107,1.286096,0.646361,1.250959,1.973113,0.763597,9.457503,1.448893,15.937822,143.09088,1.584096,2.873130,2.603871,5.28207,2.702688,0.595491,0.742576,3.985290,0.748225,0.881031,0.740779,1.571266,0.841558,1.543908,31.064078,13.343192,8.777443,3.79513,1.606069,0.049806,0.127095,16.961732,5.935678,7.029966,4.264344,1.652965,0.056568,0.123851,3.387241,0.0,3.054397,8.978994,7.253270,4.621680,14.386201,0.753293,5.164664,2.959538,5.496614,1.328581,3.387241,0.0,3.054397,8.456711,7.608319,4.746733,14.19713,0.781311,2.959538,5.164664,5.496614,1.328581,0.201941,20.366326,21.678338,4.865569,33.761129,14.039821,18.022039,NaN,NaN,0.535529,0.201941,22.522329,19.513043,4.732564,27.224539,17.385785,17.127378,NaN,NaN,0.494204,1.448893,1.448893,143.09088,2.959538,0.943134,5.913682,4.809076,13.646256,1.896245,0.807764,0.757937,1.429024,24.213937,0.742576,0.595491,0.371288,0.144338,36.113212,1.448893,1.448893,143.09088,5.164664,0.704119,13.095124,8.660228,14.069659,0.757937,0.807764,1.896245,0.874937,26.394455,0.797825,0.630209,0.308709,0.144338,37.161168
min,NaN,NaN,17.000000,25.300000,30.000000,3.000000,33.000000,270.00000,3.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.000000,26.100000,33.700000,3.000000,33.000000,270.00000,3.000000,1.000000,0.000000,1.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.120000,0.000000,0.190000,0.120000,0.190000,17.000000,2.000000,9.500000,5.67000,0.670000,0.000000,0.000000,25.000000,7.000000,16.300000,5.400000,1.200000,0.020000,0.100000,90.000000,100.0,73.000000,17.000000,12.000000,12.000000,28.000000,0.000000,0.000000,1.000000,-11.000000,-3.670000,90.000000,100.0,73.000000,17.000000,12.000000,13.000000,25.00000,0.130000,1.000000,0.000000,-13.000000,-1.560000,0.000000,25.000000,21.000000,1.000000,22.000000,15.000000,19.000000,NaN,NaN,0.000000,0.000000,25.000000,25.000000,2.000000,26.000000,10.000000,18.000000,NaN,NaN,0.000000,3.000000,3.000000,270.00000,1.000000,0.120000,7.000000,4.000000,33.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,270.00000,0.000000,0.000000,2.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,20.000000,26.875000,40.750000,3.000000,33.000000,270.00000,3.000000,2.000000,1.750000,4.000000,2.00000,0.000000,0.000000,4.000000,0.000000,0.670000,0.427500,1.280000,0.670000,1.280000,20.000000,27.300000,44.675000,3.000000,33.000000,270.00000,3.000000,4.000000,3.000000,7.00000,4.000000,0.000000,0.000000,3.000000,0.000000,0.940000,0.690000,1.670000,0.935000,1.657500,32.000000,8.000000,26.125000,9.56500,2.330000,0.060000,0.227500,43.000000,14.750000,30.750000,10.145000,3.427500,0.080000,0.237500,90.000000,100.0,80.000000,20.000000,15.000000,19.000000,31.500000,0.730000,2.000000,4.000000,-3.250000,-1.000000,90.000000,100.0,80.000000,19.000000,15.000000,19.000000,30.00000,1.000000,4.000000,2.000000,-4.000000,-0.660000,0.000000,34.250000,31.000000,4.000000,43.750000,26.500000,29.750000,NaN,NaN,0.000000,0.000000,32.000000,32.500000,4.000000,50.500000,25.750000,30.500000,NaN,NaN,0.000000,3.000000,3.000000,270.00000,4.000000,1.000000,13.750000,8.000000,54.500000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,270.00000,2.000000,0.670000,8.000000,6.000000,58.200000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,22.000000,27.900000,49.800000,4.000000,44.000000,360.00000,4.000000,5.000000,3.000000,8.000000,4.00000,0.000000,0.000000,5.000000,0.000000,1.250000,0.800000,2.000000,1.000000,2.000000,22.000000,27.800000,50.300000,4.000000,44.000000,360.00000,4.000000,5.000000,4.000000,10.00000,5.000000,0.000000,0.000000,4.000000,0.000000,1.250000,1.000000,2.330000,1.250000,2.330000,44.500000,14.500000,32.750000,10.94500,3.670000,0.110000,0.325000,49.500000,18.000000,33.650000,12.125000,4.330000,0.110000,0.310000,90.000000,100.0,82.000000,24.000000,20.000000,22.000000,39.000000,1.000000,5.000000,6.000000,-1.000000,-0.240000,90.000000,100.0,82.000000,25.000000,19.000000,21.000000,40.00000,1.635000,6.000000,5.000000,1.000000,0.240000,0.000000,45.500000,42.500000,7.000000,60.000000,33.000000,37.500000,NaN,NaN,0.000000,0.000000,45.000000,44.000000,6.500000,68.000000,30.000000,37.000000,NaN,NaN,0.000000,4.000000,4.000000,360.00000,6.000000,1.280000,18.000000,11.500000,65.600000,1.000000,1.000000,2.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,4.000000,360.00000,5.000000,1.250000,15.000000,10.000000,66.700000,2.000000,1.000000,1.000000,1.000000,29.150000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,23.000000,28.825000,55.425000,5.000000,55.000000,450.00000,5.000000,10.000000,7.250000,16.250000,9.00000,1.000000,1.000000,7.000000,1.000000,1.762500,1.405000,3.062500,1.762500,3.050000,23.000000,28.500000,59.250000,5.000000,55.000000,450.00000,5.000000,8.250000,6.000000,16.00000,8.000000,1.000000,1.000000,8.000000,0.000000,2.020000,1.390000,3.265000,1.690000,3.207500,69.250000,23.750000,38.650000,13.43750,5.020000,0.132500,0.392500,65.500000,22.000000,39.325000,14.500000,5.142500,0.160000,0.405000,95.000000,100.0,84.000000,31.000000,24.250000,25.250000,48.000000,1.807500,10.000000,9.000000,4.000000,0.660000,95.000000,100.0,84.000000,31.000000,23.250000,25.000000,50.00000,2.000000,9.000000,10.000000,3.250000,1.000000,0.000000,58.250000,60.000000,9.250000,83.750000,44.000000,48.250000,NaN,NaN,0.000000,0.000000,62.000000,57.250000,10.000000,87.500000,41.000000,52.250000,NaN,NaN,0.250000,5.000000,5.000000,450.00000,9.000000,2.020000,22.000000,15.250000,75.300000,2.250000,1.000000,2.000000,2.000000,40.000000,1.000000,1.000000,0.000000,0.000000,16.650000,5.000000,5.000000,450.00000,10.000000,1.850000,24.750000,15.500000,75.000000,2.000000,1.000000,2.250000,2.000000,50.000000,1.000000,1.000000,0.000000,0.000000,50.000000
max,NaN,NaN,25.000000,31.700000,66.300000,8.000000,88.000000,810.00000,9.000000,20.000000,18.000000,38.000000,19.00000,3.000000,3.000000,15.000000,2.000000,2.540000,2.310000,4.850000,2.370000,4.620000,25.000000,30.000000,70.000000,8.000000,88.000000,810.00000,9.000000,12.000000,10.000000,22.00000,11.000000,2.000000,3.000000,20.000000,4.000000,3.670000,3.330000,7.000000,3.670000,7.000000,140.000000,59.000000,48.400000,23.67000,7.370000,0.240000,0.620000,99.000000,33.000000,50.000000,24.000000,10.000000,0.250000,0.580000,101.000000,100.0,89.000000,55.000000,42.000000,33.000000,87.000000,2.750000,20.000000,12.000000,13.000000,1.560000,101.000000,100.0,89.000000,49.000000,42.000000,39.000000,80.00000,3.000000,12.000000,20.000000,11.000000,3.670000,1.000000,113.000000,116.000000,22.000000,165.000000,82.000000,93.000000,NaN,NaN,2.000000,1.000000,117.000000,109.000000,24.000000,151.000000,90.000000,89.000000,NaN,NaN,2.000000,8.000000,8.000000,810.00000,12.000000,4.000000,32.000000,23.000000,90.900000,7.000000,3.000000,3.000000,7.000000,87.500000,3.000000,2.000000,2.000000,1.000000,100.000000,8.000000,8.000000,810.00000,20.000000,2.540000,58.000000,40.000000,100.000000,3.000000,3.000000,7.000000,3.000000,100.000000,3.000000,3.000000,1.000000,1.000000,100.000000

============================================================
MATCHES
============================================================

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,attendance,venue,referee,home_formation,away_formation,home_manager,away_manager,home_captain,away_captain,home_possession,away_possession,home_sot,away_sot,home_total_shots,away_total_shots,home_saves,away_saves,home_cards_yellow,away_cards_yellow,home_cards_red,away_cards_red,home_fouls,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
count,104,72.000000,104,104,104,104,104,104,100.000000,100.00000,104,104,104,104,104,104,104,104,104,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,99.000000,99.000000,9
unique,7,NaN,7,34,14,48,48,31,NaN,NaN,50,17,43,10,10,48,49,52,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
top,Group stage,NaN,Sat,2026-06-24,12:00,France,Morocco,2–1,NaN,NaN,"80,663","AT&T Stadium, Arlington",Slavko Vinčič,4-2-3-1,4-2-3-1,Didier Deschamps,Mohamed Ouahbi,Kylian Mbappé,Achraf Hakimi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Required Extra Time
freq,72,NaN,19,6,23,6,5,9,NaN,NaN,7,9,4,34,34,6,5,6,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
mean,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.760000,1.26000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.423077,47.701923,4.846154,3.673077,14.019231,10.769231,2.403846,3.125000,1.153846,1.509615,0.038462,0.105769,11.625000,11.567308,5.182692,3.961538,17.817308,14.201923,8.086538,8.634615,1.919192,1.797980,NaN
std,NaN,0.822226,NaN,NaN,NaN,NaN,NaN,NaN,1.518372,1.25223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.101317,13.093302,3.108926,2.502202,6.422020,5.846301,1.913261,2.510899,1.021794,1.343775,0.193239,0.366518,4.027063,4.403803,3.409764,2.661933,10.338696,7.325153,3.859450,3.128503,1.523133,1.597062,NaN
min,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.000000,21.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,0.000000,4.000000,1.000000,1.000000,3.000000,0.000000,0.000000,NaN
25%,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.000000,38.000000,2.000000,2.000000,8.750000,7.000000,1.000000,1.750000,0.000000,1.000000,0.000000,0.000000,9.000000,8.000000,3.000000,2.000000,11.750000,9.000000,5.000000,6.000000,1.000000,1.000000,NaN
50%,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.500000,47.500000,4.000000,3.000000,13.000000,10.000000,2.000000,3.000000,1.000000,1.000000,0.000000,0.000000,11.000000,12.000000,4.000000,4.000000,15.000000,13.000000,7.500000,8.500000,2.000000,1.000000,NaN
75%,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,2.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.000000,57.000000,7.000000,5.000000,19.000000,14.000000,3.000000,4.000000,2.000000,2.000000,0.000000,0.000000,13.250000,14.000000,7.000000,5.000000,22.000000,18.000000,10.000000,11.000000,3.000000,3.000000,NaN
max,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,6.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.000000,76.000000,15.000000,11.000000,32.000000,35.000000,9.000000,15.000000,4.000000,7.000000,1.000000,2.000000,24.000000,25.000000,19.000000,14.000000,56.000000,47.000000,21.000000,16.000000,8.000000,6.000000,NaN

In [12]:
print("Players Memory Usage")

display(players.memory_usage(deep=True))

print()

print("Teams Memory Usage")

display(teams.memory_usage(deep=True))

print()

print("Matches Memory Usage")

display(matches.memory_usage(deep=True))

Players Memory Usage

Index                            132
player                        101140
team                           84864
team_country                   83070
position                       74208
age                             9984
birth_year                      9984
club                           73018
games                           9984
games_starts                    9984
minutes                         9984
minutes_90s                     9984
goals                           9984
assists                         9984
goals_assists                   9984
goals_pens                      9984
pens_made                       9984
pens_att                        9984
cards_yellow                    9984
cards_red                       9984
goals_per90                     9984
assists_per90                   9984
goals_assists_per90             9984
goals_pens_per90                9984
goals_assists_pens_per90        9984
shots                           9984
shots_on_target                 9984
shots_on_target_pct             9984
shots_per90                     9984
shots_on_target_per90           9984
goals_per_shot                  9984
goals_per_shot_on_target        9984
minutes_per_game                9984
minutes_pct                     9984
minutes_per_start               9984
games_complete                  9984
games_subs                      9984
minutes_per_sub                 9984
unused_subs                     9984
points_per_game                 9984
on_goals_for                    9984
on_goals_against                9984
plus_minus                      9984
plus_minus_per90                9984
plus_minus_wowy                 9984
cards_yellow_red                9984
fouls                           9984
fouled                          9984
offsides                        9984
crosses                         9984
interceptions                   9984
tackles_won                     9984
pens_won                        9984
pens_conceded                   9984
own_goals                       9984
gk_games                        9984
gk_games_starts                 9984
gk_minutes                      9984
gk_goals_against                9984
gk_goals_against_per90          9984
gk_shots_on_target_against      9984
gk_saves                        9984
gk_save_pct                     9984
gk_wins                         9984
gk_ties                         9984
gk_losses                       9984
gk_clean_sheets                 9984
gk_clean_sheets_pct             9984
gk_pens_att                     9984
gk_pens_allowed                 9984
gk_pens_saved                   9984
gk_pens_missed                  9984
gk_pens_save_pct                9984
dtype: int64

Teams Memory Usage

Index                        132
team                        3264
team_country                3195
players_used                 384
avg_age                      384
                            ...
gk_pens_att_against          384
gk_pens_allowed_against      384
gk_pens_saved_against        384
gk_pens_missed_against       384
gk_pens_save_pct_against     384
Length: 137, dtype: int64

Matches Memory Usage

Index                  132
round                 7084
gameweek               832
dayofweek             6240
date                  6968
start_time            6448
home_team             6965
away_team             7044
score                 9848
home_score             832
away_score             832
attendance            6552
venue                 9037
referee               9002
home_formation        6618
away_formation        6608
home_manager          8257
away_manager          8346
home_captain          8587
away_captain          8530
home_possession        832
away_possession        832
home_sot               832
away_sot               832
home_total_shots       832
away_total_shots       832
home_saves             832
away_saves             832
home_cards_yellow      832
away_cards_yellow      832
home_cards_red         832
away_cards_red         832
home_fouls             832
away_fouls             832
home_corners           832
away_corners           832
home_crosses           832
away_crosses           832
home_interceptions     832
away_interceptions     832
home_offsides          832
away_offsides          832
notes                 3859
dtype: int64

In [13]:
summary = pd.DataFrame({
    "Dataset": ["Players", "Teams", "Matches"],
    "Rows": [
        players.shape[0],
        teams.shape[0],
        matches.shape[0]
    ],
    "Columns": [
        players.shape[1],
        teams.shape[1],
        matches.shape[1]
    ],
    "Duplicate Rows": [
        players.duplicated().sum(),
        teams.duplicated().sum(),
        matches.duplicated().sum()
    ]
})

summary

   Dataset  Rows  Columns  Duplicate Rows
0  Players  1248       72               0
1    Teams    48      136               0
2  Matches   104       42               0

In [14]:
summary.to_csv(
    "../reports/dataset_summary.csv",
    index=False
)

print("Dataset Summary Saved Successfully")

Dataset Summary Saved Successfully

In [15]:
players.info()

<class 'pandas.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 72 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   player                      1248 non-null   str
 1   team                        1248 non-null   str
 2   team_country                1248 non-null   str
 3   position                    1248 non-null   str
 4   age                         1248 non-null   int64
 5   birth_year                  1248 non-null   int64
 6   club                        907 non-null    str
 7   games                       1248 non-null   int64
 8   games_starts                1248 non-null   int64
 9   minutes                     1039 non-null   float64
 10  minutes_90s                 1039 non-null   float64
 11  goals                       1039 non-null   float64
 12  assists                     1039 non-null   float64
 13  goals_assists               1039 non-null   float64
 14  goals_pens                  1039 non-null   float64
 15  pens_made                   1039 non-null   float64
 16  pens_att                    1039 non-null   float64
 17  cards_yellow                1039 non-null   float64
 18  cards_red                   1039 non-null   float64
 19  goals_per90                 1039 non-null   float64
 20  assists_per90               1039 non-null   float64
 21  goals_assists_per90         1039 non-null   float64
 22  goals_pens_per90            1039 non-null   float64
 23  goals_assists_pens_per90    1039 non-null   float64
 24  shots                       1039 non-null   float64
 25  shots_on_target             1039 non-null   float64
 26  shots_on_target_pct         680 non-null    float64
 27  shots_per90                 1039 non-null   float64
 28  shots_on_target_per90       1039 non-null   float64
 29  goals_per_shot              680 non-null    float64
 30  goals_per_shot_on_target    396 non-null    float64
 31  minutes_per_game            1039 non-null   float64
 32  minutes_pct                 1039 non-null   float64
 33  minutes_per_start           781 non-null    float64
 34  games_complete              1248 non-null   int64
 35  games_subs                  1248 non-null   int64
 36  minutes_per_sub             578 non-null    float64
 37  unused_subs                 1248 non-null   int64
 38  points_per_game             1039 non-null   float64
 39  on_goals_for                1039 non-null   float64
 40  on_goals_against            1039 non-null   float64
 41  plus_minus                  1039 non-null   float64
 42  plus_minus_per90            1039 non-null   float64
 43  plus_minus_wowy             920 non-null    float64
 44  cards_yellow_red            1039 non-null   float64
 45  fouls                       1039 non-null   float64
 46  fouled                      1039 non-null   float64
 47  offsides                    1039 non-null   float64
 48  crosses                     1039 non-null   float64
 49  interceptions               1039 non-null   float64
 50  tackles_won                 1039 non-null   float64
 51  pens_won                    0 non-null      float64
 52  pens_conceded               0 non-null      float64
 53  own_goals                   1039 non-null   float64
 54  gk_games                    62 non-null     float64
 55  gk_games_starts             62 non-null     float64
 56  gk_minutes                  62 non-null     float64
 57  gk_goals_against            62 non-null     float64
 58  gk_goals_against_per90      62 non-null     float64
 59  gk_shots_on_target_against  62 non-null     float64
 60  gk_saves                    62 non-null     float64
 61  gk_save_pct                 59 non-null     float64
 62  gk_wins                     62 non-null     float64
 63  gk_ties                     62 non-null     float64
 64  gk_losses                   62 non-null     float64
 65  gk_clean_sheets             62 non-null     float64
 66  gk_clean_sheets_pct         58 non-null     float64
 67  gk_pens_att                 62 non-null     float64
 68  gk_pens_allowed             62 non-null     float64
 69  gk_pens_saved               62 non-null     float64
 70  gk_pens_missed              62 non-null     float64
 71  gk_pens_save_pct            15 non-null     float64
dtypes: float64(60), int64(7), str(5)
memory usage: 702.1 KB

In [16]:
teams.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Columns: 136 entries, team to gk_pens_save_pct_against
dtypes: float64(42), int64(92), str(2)
memory usage: 51.1 KB

In [17]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   round               104 non-null    str
 1   gameweek            72 non-null     float64
 2   dayofweek           104 non-null    str
 3   date                104 non-null    str
 4   start_time          104 non-null    str
 5   home_team           104 non-null    str
 6   away_team           104 non-null    str
 7   score               104 non-null    str
 8   home_score          100 non-null    float64
 9   away_score          100 non-null    float64
 10  attendance          104 non-null    str
 11  venue               104 non-null    str
 12  referee             104 non-null    str
 13  home_formation      104 non-null    str
 14  away_formation      104 non-null    str
 15  home_manager        104 non-null    str
 16  away_manager        104 non-null    str
 17  home_captain        104 non-null    str
 18  away_captain        104 non-null    str
 19  home_possession     104 non-null    int64
 20  away_possession     104 non-null    int64
 21  home_sot            104 non-null    int64
 22  away_sot            104 non-null    int64
 23  home_total_shots    104 non-null    int64
 24  away_total_shots    104 non-null    int64
 25  home_saves          104 non-null    int64
 26  away_saves          104 non-null    int64
 27  home_cards_yellow   104 non-null    int64
 28  away_cards_yellow   104 non-null    int64
 29  home_cards_red      104 non-null    int64
 30  away_cards_red      104 non-null    int64
 31  home_fouls          104 non-null    int64
 32  away_fouls          104 non-null    int64
 33  home_corners        104 non-null    int64
 34  away_corners        104 non-null    int64
 35  home_crosses        104 non-null    int64
 36  away_crosses        104 non-null    int64
 37  home_interceptions  104 non-null    int64
 38  away_interceptions  104 non-null    int64
 39  home_offsides       99 non-null     float64
 40  away_offsides       99 non-null     float64
 41  notes               9 non-null      str
dtypes: float64(5), int64(20), str(17)
memory usage: 34.3 KB